"""
data/train_priority_model.py — XGBoost Priority Model Training Script
======================================================================
OpRail | SIH 2026 | PS-26027

Trains an XGBoost regressor to predict maintenance priority scores.

WHY XGBoost over the weighted formula?
  The weighted formula is linear. XGBoost can capture nonlinear interactions:
  e.g., "severity matters FAR MORE when both overdue_days AND train_density
  are simultaneously high" — this interaction can't be expressed as a simple
  weighted sum, but a tree model learns it naturally.

HONEST LABEL DISCLOSURE (for PPT):
  Labels are generated by the V1 formula (compute_priority_score) since no
  historical incident/outcome data exists. The XGBoost model therefore learns
  a smoothed, nonlinear approximation of the V1 formula, NOT independent
  ground truth. We state this explicitly in our presentation.
  In production, labels would come from actual maintenance outcome data
  (e.g., time-to-failure, CAG audit results) — this is V2's upgrade path.

Usage:
    python data/train_priority_model.py
    → saves models/priority_model.pkl
"""
import os
import sys
import pickle

# Fix Windows CP1252 console so emoji in print() works without PYTHONUTF8
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

try:
    import xgboost as xgb
    import shap
    HAS_XGBOOST = True
except ImportError:
    HAS_XGBOOST = False
    print("⚠️  XGBoost not installed — run: pip install xgboost shap")

from app.services.priority_engine import compute_priority_score

MODELS_DIR = os.path.join(os.path.dirname(__file__), "..", "models")
MODEL_PATH = os.path.join(MODELS_DIR, "priority_model.pkl")
FEATURE_NAMES = [
    "severity",
    "days_overdue",
    "train_density",
    "asset_criticality",
    "is_safety_critical",
    "requires_ohe_disconnection",
    "duration_minutes_normalized",
]


def generate_training_data(n_samples: int = 10_000) -> pd.DataFrame:
    """
    Generate synthetic training samples covering the full parameter space.
    Labels are V1 priority scores. XGBoost will learn nonlinear interactions
    between features that the V1 formula treats as independent.
    """
    np.random.seed(42)

    severity = np.random.randint(1, 6, n_samples)           # 1-5
    days_overdue = np.random.exponential(scale=25, size=n_samples).astype(int)
    days_overdue = np.clip(days_overdue, 0, 365)
    train_density = np.random.beta(3, 2, n_samples)          # skewed toward 0.6-0.9
    asset_criticality = np.random.randint(1, 6, n_samples)   # 1-5
    is_safety_critical = (severity >= 4).astype(int)
    requires_ohe = np.random.binomial(1, 0.35, n_samples)
    duration_norm = np.random.choice([30, 45, 60, 90, 120, 150, 180], n_samples) / 180.0

    # V1 priority labels
    labels = np.array([
        compute_priority_score(
            severity=int(s),
            days_overdue=int(d),
            train_density=float(td),
            asset_criticality=int(ac),
        )
        for s, d, td, ac in zip(severity, days_overdue, train_density, asset_criticality)
    ])

    # Add realistic noise — simulates human judgment variance
    noise = np.random.normal(0, 2.0, n_samples)
    labels = np.clip(labels + noise, 0, 100)

    df = pd.DataFrame({
        "severity": severity,
        "days_overdue": days_overdue,
        "train_density": train_density,
        "asset_criticality": asset_criticality,
        "is_safety_critical": is_safety_critical,
        "requires_ohe_disconnection": requires_ohe,
        "duration_minutes_normalized": duration_norm,
        "priority_score": labels,
    })
    return df


def train_model(df: pd.DataFrame):
    X = df[FEATURE_NAMES]
    y = df["priority_score"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = xgb.XGBRegressor(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        n_jobs=-1,
        verbosity=0,
    )
    model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)

    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    return model, mae, r2, X_test, y_test


def compute_shap_values(model, X_test: pd.DataFrame) -> dict:
    """Compute SHAP feature importance for explainability panel.
    
    Compatibility note: SHAP 0.46 doesn't fully support XGBoost 3.x sklearn wrapper.
    Passing model.get_booster() (the raw booster) to TreeExplainer works around this.
    """
    try:
        # Pass raw booster to avoid SHAP 0.46 / XGBoost 3.x base_score incompatibility
        explainer = shap.TreeExplainer(model.get_booster())
        shap_values = explainer.shap_values(X_test)
        importance = dict(zip(FEATURE_NAMES, np.abs(shap_values).mean(axis=0).tolist()))
    except Exception:
        # Fallback: use native XGBoost feature importance if SHAP fails
        importance_raw = model.get_booster().get_score(importance_type='gain')
        # Normalize to 0-1 scale
        total = sum(importance_raw.values()) or 1
        importance = {f: importance_raw.get(f, 0.0) / total for f in FEATURE_NAMES}
    return dict(sorted(importance.items(), key=lambda x: x[1], reverse=True))


def main():
    if not HAS_XGBOOST:
        sys.exit(1)

    os.makedirs(MODELS_DIR, exist_ok=True)

    print("🤖 OpRail — XGBoost Priority Model Training")
    print("=" * 55)
    print("Generating 10,000 synthetic training samples...")
    df = generate_training_data(10_000)
    print(f"   Score range: {df['priority_score'].min():.1f} – {df['priority_score'].max():.1f}")
    print(f"   Mean score:  {df['priority_score'].mean():.1f}")

    print("\nTraining XGBoost regressor (300 estimators)...")
    model, mae, r2, X_test, y_test = train_model(df)
    print(f"   MAE  = {mae:.3f} (mean absolute error in score points)")
    print(f"   R²   = {r2:.4f}")

    print("\nComputing SHAP feature importances...")
    shap_importance = compute_shap_values(model, X_test)
    print("   Feature importance (SHAP mean |φ|):")
    for feat, val in shap_importance.items():
        bar = "█" * int(val * 2)
        print(f"   {feat:<35} {bar} {val:.3f}")

    # Save model + metadata
    artifact = {
        "model": model,
        "feature_names": FEATURE_NAMES,
        "shap_importance": shap_importance,
        "metrics": {"mae": mae, "r2": r2},
        "version": "v2_xgboost",
        "label_source": "V1 weighted formula (compute_priority_score) with Gaussian noise σ=2.0",
    }
    with open(MODEL_PATH, "wb") as f:
        pickle.dump(artifact, f)

    print(f"\n✅ Model saved to {MODEL_PATH}")
    print("\n📌 PPT Note:")
    print("   Labels are V1-formula derived. XGBoost learns nonlinear")
    print("   feature interactions (severity×overdue×density) that the")
    print("   linear formula cannot express. State this explicitly.")
    print("   In production: replace with real maintenance outcome labels.")


if __name__ == "__main__":
    main()
